/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LayoutAuth: typeof import('./src/layouts/LayoutAuth.vue')['default']
    LayoutError: typeof import('./src/layouts/LayoutError.vue')['default']
    LayoutMain: typeof import('./src/layouts/LayoutMain.vue')['default']
    MConfirmAction: typeof import('./src/shared/modals/confirm-action/MConfirmAction.vue')['default']
    ModalContainer: typeof import('./src/shared/modals/ModalContainer.vue')['default']
    NApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_6f0fc43fb43b9475c6385063786355ee/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    NButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_6f0fc43fb43b9475c6385063786355ee/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    NCheckbox: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_6f0fc43fb43b9475c6385063786355ee/node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    NForm: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_6f0fc43fb43b9475c6385063786355ee/node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    NFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_6f0fc43fb43b9475c6385063786355ee/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    NInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_6f0fc43fb43b9475c6385063786355ee/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    NModal: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_6f0fc43fb43b9475c6385063786355ee/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    NNavigationMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_6f0fc43fb43b9475c6385063786355ee/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    NSkeleton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_6f0fc43fb43b9475c6385063786355ee/node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
    QAuth: typeof import('./src/pages/auth/QAuth.vue')['default']
    QMain: typeof import('./src/pages/main/QMain.vue')['default']
    QPageNotFound: typeof import('./src/pages/errors/QPageNotFound.vue')['default']
    QUser: typeof import('./src/pages/user/QUser.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UButton: typeof import('./src/shared/ui/form/UButton.vue')['default']
    UInput: typeof import('./src/shared/ui/form/UInput.vue')['default']
    UInputPassword: typeof import('./src/shared/ui/form/UInputPassword.vue')['default']
    UModal: typeof import('./src/shared/ui/UModal.vue')['default']
    UNav: typeof import('./src/layouts/ui/UNav.vue')['default']
  }
}
